### PR TITLE
Issue 38

### PR DESCRIPTION
**Pull request by dcallao**
issue #38 

Changes:
- new ELB at port 80
- new S3 bucket for ELB access logs
- new S3 bucket policy to allow ELB to save logs into new bucket
- added ELB account IDs
- updated all AMI ID of each region in AMI ID map
- added ELB URL endpoint in Outputs

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by avattathil** [comment]
Did the final test pass?

**Comment by dcallao** [comment]
@gargana @avattathil My tests pass as far as the changes introduced in this PR. I see this small signal error referring to a separate issue outside this PR: ```ValidationError: Stack arn:aws:cloudformation:us-west-2:795541454942:stack/test-consul-stack/e3a1d540-3322-11ea-aedb-06ac44ac494e is in CREATE_COMPLETE state and cannot be signaled``` Please verify then merge.

**Comment by avattathil** [comment]
look good now, merging to develop and running CI teats

**Comment by avattathil** [comment]
@gargana you can add the cert on top

**Pull request merged**
