### PR TITLE
Update for Dead Server Cleanup features in Consul 0.8.

### PR DESCRIPTION
**Pull request by clstokes**
- Removes force-leaves scripts that are no longer needed.
- ~~Removes IAM resources that are no longer needed.~~
- Updates submodules to latest.
- Updates consul-template to 0.18.2.

### CODE REVIEW

**Comment by clstokes** [comment]
Actually, this isn't ready. Please hold..

**Comment by clstokes** [comment]
Ok, good to go!

**Comment by avattathil** [comment]
@erin Please make the changes needed per your previous comments in https://github.com/aws-quickstart/quickstart-hashicorp-consul/pull/8.

**Comment by emcfins** [comment]
btw 👍 was able to launch with no problem

**Pull request merged**
